program: train.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  BATCH_SIZE:
    value: 32
  MAX_LEN:
    values: [64, 128]
  LEARNING_RATE:
    min: 0.0001
    max: 0.1
  EPOCHS:
    value: 20