project: LEVEL1_STS
program: train.py
method: bayes
metric:
  name: val_pearson_corr
  goal: maximize
parameters:
  EPOCHS:
    value: 20
  BATCH_SIZE:
    value: 32
  MAX_LEN:
    value: 128
  LEARNING_RATE:
    min: 0.0001
    max: 0.0005
  LORA_RANK:
    values: [8, 16, 32, 64]
  MODEL_NAME:
    value: Dongjin-kr/ko-reranker
  MODULE_NAMES:
    value: ['query', 'key', 'value']
  SEED:
    value: 42
  DATA_DIR:
    value: './data'