project: LEVEL1_STS
program: train.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  BATCH_SIZE:
    value: 32
  MAX_LEN:
    values: [64, 128]
  LEARNING_RATE:
    min: 0.0001
    max: 0.001
  EPOCHS:
    value: 20
  MODEL_NAME:
    value: 'FacebookAI/xlm-roberta-large'
  SEED:
    value: 12345
  DATA_DIR:
    value: './data'