project: LEVEL1_STS
program: train.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  EPOCHS:
    value: 20
  BATCH_SIZE:
    values: [16, 32, 64]
  MAX_LEN:
    values: [64, 128]
  LEARNING_RATE:
    min: 0.0001
    max: 0.0005
  LORA_RANK:
    values: [8, 16, 32, 64]
  MODEL_NAME:
    value: klue/roberta-large
  MODULE_NAMES:
    value: ['query', 'key', 'value']
  SEED:
    value: 42
  DATA_DIR:
    value: './data'